apiVersion: v1
kind: ReplicationController
metadata:
  name: faulty
spec:
  replicas: 1
  selector:
    name: faulty
  template:
    metadata:
      labels:
        name: faulty
        app: lbtest
    spec:
      containers:
      - name: nginx
        image: tback/lbtest:faulty
        ports:
        - containerPort: 80
